[project]
name = "models"
version = "0.1.0"
description = "Python Pydantic models that are shared between the API and the backend."
authors = [
    {name = "Siddharth Rao", email = "siddrao.926@gmail.com"},
]
dependencies = ["isort>=5.13.2", "black>=24.10.0", "flake8>=7.1.1"]
requires-python = ">=3.13"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true
