[project]
name = "roboskill"
version = "0.1.0"
description = "A rating system built for FIRST's FRC and FTC matches."
authors = [
    {name = "Siddharth Rao", email = "siddrao.926@gmail.com"},
]
dependencies = ["numpy>=2.2.0", "pandas>=2.2.3"]
requires-python = ">=3.13"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true
