name: Backend | Lint (flake8, black, isort)

on:
    push:
        paths:
            - "apps/backend/**"
    pull_request:
        paths:
            - "apps/backend/**"

jobs:
    lint:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: apps/backend

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4.2.2

            - name: Set up Python
              uses: actions/setup-python@v5.3.0
              with:
                  python-version: "3.12.4"

            - name: Cache PDM Dependencies
              uses: actions/cache@v4.1.2
              with:
                  path: ~/.cache/pdm
                  key: ${{ runner.os }}-pdm-${{ hashFiles('apps/backend/pdm.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-pdm-

            - name: Install Dependencies
              run: pdm install -G lint

            - name: Lint with flake8
              run: pdm run flake8 src/

            - name: Lint with black
              run: pdm run black --check .

            - name: Lint with isort
              run: pdm run isort --check-only .
