name: Python Models | Lint (flake8, black, isort)

on:
    push:
        paths:
            - "packages/python-models/**"
    pull_request:
        paths:
            - "packages/python-models/**"

jobs:
    lint:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: packages/python-models

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4.2.2

            - name: Set up Python
              uses: actions/setup-python@v5.3.0
              with:
                  python-version: "3.12.4"

            - name: Cache PDM Dependencies
              uses: actions/cache@v4.2.0
              with:
                  path: ~/.cache/pdm/python-models
                  key: ${{ runner.os }}-pdm-${{ hashFiles('apps/python-models/pdm.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-pdm-

            - name: Install PDM
              run: python -m pip install pdm

            - name: Install Dependencies
              run: pdm install -G lint

            - name: Lint with flake8
              run: pdm run flake8 ./src

            - name: Lint with black
              run: pdm run black --check .

            - name: Lint with isort
              run: pdm run isort --check-only .
